name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'
    - name: Clear pip cache
      run: |
        rm -rf ~/.cache/pip  # Удаление кэша pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint pygame pyfakefs
    - name: Install project dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
    - name: Run unittests
      run: |
        python -m unittest discover .
